---
spring:
  profiles: default
  application:
    name: ms-xmen
    dna:
      default-size-arr: 6
      default-count-mutant: 2
      default-diagonal-size: 6
  datasource:
    driverClassName: org.h2.Driver
    url: "jdbc:h2:mem:%s;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    password: "root"
    username: "root"
    testOnBorrow: true
    testWhileIdle: true
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
---
spring:
  profiles: production
  application:
    name: ms-xmen
    dna:
      default-size-arr: 6
      default-count-mutant: 2
      default-diagonal-size: 6
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://google/xmendb?cloudSqlInstance=mercado-libre-331317:southamerica-east1:xmendbinstance&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=root&password=root"
    password: "root"
    username: "root"
    testOnBorrow: true
    testWhileIdle: true
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000